// Subsets of @fontsource Inter and JetBrains Mono (OFL), regenerated by assets/fonts/subset.sh.
import inter400 from '../assets/fonts/inter-400.woff2';
import inter500 from '../assets/fonts/inter-500.woff2';
import mono400 from '../assets/fonts/jetbrains-mono-400.woff2';
import mono500 from '../assets/fonts/jetbrains-mono-500.woff2';

/** Family names private to webscoop, so a host font with the same name never wins. */
export const SANS = 'Webscoop Inter';
export const MONO = 'Webscoop Mono';

/**
 * Register the embedded fonts on the document. `@font-face` inside a shadow
 * root is ignored by Chromium, so the faces go through the FontFace API.
 */
export function loadFonts(doc: Document = document): void {
  if (typeof FontFace === 'undefined' || !doc.fonts) return;
  const faces: [string, Uint8Array, string][] = [
    [SANS, inter400, '400'],
    [SANS, inter500, '500'],
    [MONO, mono400, '400'],
    [MONO, mono500, '500'],
  ];
  for (const [family, bytes, weight] of faces) {
    const face = new FontFace(family, bytes as unknown as ArrayBuffer, { weight, style: 'normal' });
    doc.fonts.add(face);
    void face.load().catch(() => {});
  }
}
